---
title: "Reinforcement Lab Declan"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Load in necessary libraries for clustering
library(e1071)
library(tidyverse)
library(plotly)
library(htmltools)
library(devtools)
library(NbClust)

#Reading in the dataset
df = read_csv("week-11-reinforcement-lab/data-summary.csv")
df1 = select(df,main_colors,opp_colors,on_play,num_turns,won)

# feature engineering (cora,corc)
df2 = select(df,"deck_Adeline, Resplendent Cathar":"deck_Wrenn and Seven")
mat = data.matrix(df2)
vec1 = vector()
vec3 = vector()
for(i in 1:nrow(mat) ){
  x=cor( mat[1,] , mat[i,])
  vec1 = c(vec1,x)
  z=cor( mat[47,] , mat[i,])
  vec3 = c(vec3,z)
}

# add new features to dataframe
df1 <- df1 %>% mutate(cora = vec1)
df1 <- df1 %>% mutate(corc = vec3)

# make scatter plot comparing new features
ggplot(df1,aes(x=cora,y=corc))+geom_point()

```

Using K-Means to derive information

```{r}
normalize = function(x){
 (x - min(x)) / (max(x) - min(x))
}
#Removing "Won" variable so we do not overfit the model and the main/opp colors because they are non-numeric
df1_kmeans = select(df1, c(3,4,6,7))
#Normalizing the number of turns for the kmeans modeling algorithm
df1_kmeans$num_turns = normalize(df1_kmeans$num_turns)
#Changing Boolean to Numeric
df1_kmeans$on_play = as.numeric(df1_kmeans$on_play)


#Creating the initial model
set.seed(3001)
kmeans_obj_df1 = kmeans(df1_kmeans, centers = 5, 
                        algorithm = "Lloyd")
kmeans_obj_df1

clusters_df1 = as.factor(kmeans_obj_df1$cluster)

ggplot(df1, aes(x = cora,
                 y = corc,
                 shape = clusters_df1,
                 color = won)) +
  geom_point(size = 6) + 
  ggtitle("5 Clusters mapped against the 'won' variable") +
  xlab("Cora") +
  ylab("Corc") +
  scale_shape_manual(name = "Cluster", 
                     labels = c("Cluster #1", "Cluster #2","Cluster #3", "Cluster #4", "Cluster #5"),
                     values = c("1", "2","3","4","5")) +
  theme_light()


df1_results = mutate(df1, cluster = clusters_df1)
df1_results %>% count(cluster, won) 

#Given the clusters we have, they do not seem to group the data by whether the player won or not

explained_variance = function(data_in, k){
  
  # Running the kmeans algorithm.
  set.seed(3001)
  kmeans_obj = kmeans(data_in, centers = k, algorithm = "Lloyd", iter.max = 30)
  
  # Variance accounted for by clusters:
  # var_exp = intercluster variance / total variance
  var_exp = kmeans_obj$betweenss / kmeans_obj$totss
  var_exp  
}

#Use the function we created to evaluate several different number of clusters
explained_var_df1 = sapply(1:10, explained_variance, data_in = df1_kmeans)

elbow_data_df1 = data.frame(k = 1:10, explained_var_df1)

ggplot(elbow_data_df1, aes(x = k,
                           y = explained_var_df1)) + 
         geom_point(size = 5)+
         geom_line(size = 2,
                  color = "blue")
  
#Maybe 4 clusters would work better!

set.seed(3001)
kmeans_obj_4clust = kmeans(df1_kmeans, centers = 4, 
                        algorithm = "Lloyd")
kmeans_obj_4clust

clusters_4clust = as.factor(kmeans_obj_4clust$cluster)

ggsave("clusters.png", ggplot(df1, aes(x = cora,
                 y = corc,
                 shape = clusters_4clust,
                 color = won)) +
  geom_point(size = 6) + 
  ggtitle("4 Clusters mapped against the 'won' variable") +
  xlab("Cora") +
  ylab("Corc") +
  scale_shape_manual(name = "Cluster", 
                     labels = c("Cluster #1", "Cluster #2","Cluster #3", "Cluster #4"),
                     values = c("1", "2","3","4")) +
  theme_light())

df1_results4 = mutate(df1, cluster = clusters_4clust)
df1_4 = count(df1_results4, cluster, won)

#Still, the number of clusters does not group by whether the player wins or loses
```

