---
title: "Survey Results"
author: "Brian Wright"
date: "8/25/2021"
output: 
  html_document: 
    toc: yes
    toc_float:
      toc_collapsed: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r,include=FALSE}
library(tidyverse)
library(data.table)

getwd()
```

```{r, include=FALSE}

#What are we doing here specifically? 

data <- fread("~/git_3001/DS-3001/data/Class_Assessment_Spring_2022_clean.csv", skip =1)

#fread is a much faster way to read in large datasets than read_csv or read.csv, its a function in the data.table package. You don't have to use fread, just presenting the option. I use read_csv throughout the class. 
View(data)

?fread
#?data.table

View(data)#What's wrong with this data....? 
#First assignment using the fread documentation fix this issue. 
```

## Let's take a look at the numeric responses 
```{r}
str(data)#str is short for structure, gives us a overview of the data

#What are we doing here and why? 
column_index <- tibble(colnames(data))
column_index

hist(data$`On a scale of 1 to 10 rank your comfort with the R programming language, generally`, main = "R Programming")


hist(data$`On a scale from 1 to 10 rank your comfort with markdown or Rmarkdown generally.`, main = "Markdown")

hist(data$`On scale from 1 to 10 rank your comfort with using tidyverse packages`, main = "Tidyverse")


hist(data$`On a scale from 1 to 10 rank your experience using machine learning models.`, main = "Machine Learning")



```

## Now let's check out the factors(what's a better appoarch) 
```{r}
x_table <- table(data$`What is your major?`)

x_table

vis <- ggplot(data, aes(y=`What is your major?`))#flipped the Cartesian coordinates for better viewing

vis
#What's the issue with this plot? 

column_index
data[[8]]#double brackets search only columns

#Creating a function for the data viz
factor_viz <- function(x,y,z){
  #x=data,y=column,z=label
  vis <- ggplot(x, aes(y=x[[y]]))+#indexing using column number
    geom_bar()+#creating a bar chart
    labs(x="Count",y=z)+#adding the labels
    theme_minimal()#changing the appearance
  vis
}




#Next task: use the function for the "Major" and "Language" columns
```








































































































































































































































```{r}
factor_viz(data,8,"Major")

factor_viz(data,9,"Language")
```

