---
title: "ml_bootcamp"
author: "Adriel Wright"
date: "9/28/2021"
output:
  html_document:
    toc: TRUE
    theme: journal
    toc_float: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
library(psych)
library(mltools)
library(data.table)
library(caret)
```
[caret documentation](http://topepo.github.io/caret/index.html)


## Phase I
[Cereal_Data_Dictionary](https://data.world/food/wine-quality)

```{r}
#Working to developed a model than can predict wine quality

#Assuming we are able to optimizing and make recommendations how does this translate into a business context? 

# Inference versus Prediction 

# Independent Business Metric - Assuming that higher wine quality ratings result in higher sales, can we predict which new wines will perform best?

```

## Phase II 

### Scale/Center/Normalizing

```{r}

wine <- read_csv("winequality-red.csv")
View(wine)
attach(wine)#is this a good idea? 
describe(wine)
?scale
str(wine)


# (sodium_c <- scale(cereal$sodium, center = TRUE, scale = FALSE))#center but not standardized
# (sodium_sc <- scale(cereal$sodium, center = TRUE, scale = TRUE))#center and standardized
#min-max scaling, placing the numbers between 0 and 1.

###Build our own normalizer, which is maybe how I would go if given the option. If you need to do multiple columns use lapply. See this referred to as a min-max scaler function.

normalize <- function(x){
 (x - min(x)) / (max(x) - min(x))
}
(column_index <- tibble(colnames(wine)))

# wine[, c(12)] <- lapply(wine[,c(12)], as.factor)
str(wine)
 
# #Now we can move forward in normalizing the numeric values, create a index based on numeric columns:
# 
numeric_vals <- names(select_if(wine, is.numeric))# select function to find the numeric variables
# 
# #Use lapply to normalize the numeric values
# 
wine[numeric_vals] <- as_tibble(lapply(wine[numeric_vals], normalize))
# 
str(wine)

```


### One-hot Encoding (No categorical attributes, so not necessary)

### Baseline/Prevalance 

```{r}
#Essential the target to which we are trying to better with our model. 
describe(wine$quality)
(box <- boxplot(wine$quality, horizontal = TRUE)) 
box$stats
fivenum(wine$quality)
?fivenum#thanks Tukey!

#added this a predictor versus replacing the numeric version
(wine$quality_f <- cut(wine$quality,c(-1,.6,1),labels = c(0,1)))

str(wine)
View(wine)
#So no let's check the prevalence 
(prevalence <- table(wine$quality_f)[[2]]/length(wine$quality_f))

```

### Initial Model Building: Decision Tree Style  

```{r}
# Training, Evaluation, Tune, Evaluation, Test, Evaluation
# Divide up our data into three parts, Training, Tuning, and Test

#There is not a easy way to create 3 partitions using the createDataPartitions

#so we are going to use it twice. Mostly because we want to stratify on the variable we are working to predict. What does that mean?  

#clean up our dataset a bit by dropping the original ranking variable and the cereal name which we can't really use. 

wine_dt <- wine[,c(1,2,3,4,5,6,7,8,9,10,11,13)]
view(wine_dt)

part_index_1 <- caret::createDataPartition(wine$quality_f,
                                           times=1,
                                           p = 0.70,
                                           groups=1,
                                           list=FALSE)
View(part_index_1)
dim(wine)

train <- wine[part_index_1,]
tune_and_test <- wine[-part_index_1, ]

#The we need to use the function again to create the tuning set 

tune_and_test_index <- createDataPartition(tune_and_test$quality_f,
                                           p = .5,
                                           list = FALSE,
                                           times = 1)

tune <- tune_and_test[tune_and_test_index, ]
test <- tune_and_test[-tune_and_test_index, ]
View(test)
View(tune)

dim(train)
dim(tune)
dim(test)
```

#### Using Caret package to fit a C5.0 version of a decision tree
Setting up the cross validation
[Caret_Documentation](http://topepo.github.io/caret/train-models-by-tag.html#Tree_Based_Model)
```{r}
#Cross validation process 

fitControl <- trainControl(method = "repeatedcv",
                          number = 10,
                          repeats = 5, 
                          returnResamp="all") 

# number - number of folds
# repeats - number of times the CV is repeated, here it's 5 take the average of
# those 5 repeats


# Choose the features and classes

```

#### Training and Evaluation 

```{r}
features <- train[,c(1,2,3,4,5,6,7,8,9,10,11)]
view(train)
target <- train[,"quality_f"]


str(target)

set.seed(1984)
wine_mdl <- train(x=features,
                y=target$quality_f,
                trControl=fitControl,
                method="C5.0",
                verbose=TRUE)

wine_mdl

```

Tune and Evaluation 
```{r}
wine_predict = predict(wine_mdl,tune,type= "raw")

confusionMatrix(as.factor(wine_predict), 
                as.factor(tune$quality_f), 
                dnn=c("Prediction", "Actual"), 
                mode = "sens_spec")

varImp(wine_mdl)

plot(wine_mdl)


grid <- expand.grid(.winnow = c(TRUE,FALSE), 
                    .trials=c(20,30,40), 
                    .model=c("tree","rules"))
set.seed(1984)
wine_mdl_tune <- train(x=features,
                y=target$quality_f,
                tuneGrid=grid,
                trControl=fitControl,
                method="C5.0",
                verbose=TRUE)

wine_mdl_tune
wine_mdl

plot(wine_mdl_tune)

# Want to evaluation again with the tune data using the new model 

wine_predict_tune = predict(wine_mdl_tune,tune,type= "raw")

confusionMatrix(as.factor(wine_predict_tune), 
                as.factor(tune$quality_f), 
                dnn=c("Prediction", "Actual"), 
                mode = "sens_spec")


```

Test 

```{r}
view(test)
view(tune)
wine_predict_test = predict(wine_mdl_tune,test,type= "raw")

confusionMatrix(as.factor(wine_predict_test), 
                as.factor(test$quality_f), 
                dnn=c("Prediction", "Actual"), 
                mode = "sens_spec")

```




